name: JSDoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir:  ${{ GITHUB_WORKSPACE }}
          output_dir:  ${{ GITHUB_WORKSPACE }}
